export const UPDATE_UPLOADED_FILES = 'UPDATE_UPLOADED_FILES';
export type UPDATE_UPLOADED_FILES = typeof UPDATE_UPLOADED_FILES;

export const FILE_UPLOADED_ACTION = 'FILE_UPLOADED_ACTION';
export type FILE_UPLOADED_ACTION = typeof FILE_UPLOADED_ACTION;