export const FILE_UPLOADED_ACTION = 'FILE_UPLOADED_ACTION';
export type FILE_UPLOADED_ACTION = typeof FILE_UPLOADED_ACTION;

export const FILES_TO_UPLOAD_ACTION = 'FILES_TO_UPLOAD_ACTION';
export type FILES_TO_UPLOAD_ACTION = typeof FILES_TO_UPLOAD_ACTION;